version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth_app_data:/data/db

  mailserver:
    image: maildev/maildev
    restart: always
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  spring_auth_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mailserver
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

volumes:
  auth_app_data: